### PR TITLE
Add DEVELOP.md dev environment setup instructions

### PR DESCRIPTION
**Pull request by ssteinerx**
Added a document showing how to set up a development environment.  

No changes to anything else.

The instructions for running the tests are great, but you need an environment to run them in!

### CODE REVIEW

**Comment by ralequi** [comment]
Thank you @ssteinerx !
Much appreciate your contribution !

**Comment by ssteinerx** [comment]
Please add me to your contributors list.  I didn't put any of my information into the document I provided as I didn't know what the policy/procedure was and forgot all about it until I was cleaning up my email!
Thanks, ssteinerX

**Comment by ralequi** [comment]
Hi @ssteinerx 

I don't have a contribution list on this project per-se but you have been recorded on the changelog.md.
It's on an un-pushed code that still need to be checked first.

I give you an screenshot so you can sleep better :-)

image

**Comment by ssteinerx** [comment]
Zzzzzzzz... ;-)

**Pull request merged**
